export const BusinessType = {
  BUILDING_SUPPLIES: "BUILDING_SUPPLIES",
  ROOFING: "ROOFING",
  GENERAL_CONTRACTING: "GENERAL_CONTRACTING",
  ENGINEERING: "ENGINEERING",
  DEMOLITION_AND_CLEANUP: "DEMOLITION_AND_CLEANUP",
  CONCRETE_AND_MASONRY: "CONCRETE_AND_MASONRY",
  PAINTING: "PAINTING",
  EXTERIOR_FINISHING: "EXTERIOR_FINISHING",
  FLOORING_SUPPLY: "FLOORING_SUPPLY",
  KITCHEN_AND_BATH: "KITCHEN_AND_BATH",
  PLUMBING: "PLUMBING",
  HEATING_AND_VENTILATION: "HEATING_AND_VENTILATION",
  ELECTRICAL: "ELECTRICAL",
  LANDSCAPING: "LANDSCAPING",
  METAL_AND_WELDING: "METAL_AND_WELDING",
} as const;

export type BusinessTypeEnum = keyof typeof BusinessType;
